name: filmapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1+7
  firebase_core: ^0.4.0+6
  flutter_facebook_login: ^2.0.1
  flutter_auth_buttons: ^0.5.0
  google_sign_in: ^4.0.2
  http: ^0.12.0+2
  flutter_swiper: ^1.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true

  assets:
    - assets/img/film.png
    - assets/img/film1.png
    - assets/img/loading.gif
    - assets/img/no-image.jpg
    - assets/img/fb.png
    - assets/img/tw.png
    

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf

